services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - ProjectNeumann_back/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  redis:
    image: redis   
    container_name: redis
    restart: unless-stopped 
    expose:
      - 6379

  node:
    container_name: node
    build: ./ProjectNeumann_back
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - ProjectNeumann_back/.env

  react:
    container_name: react
    build: ./ProjectNeumann_front
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - react

volumes:
  postgres-volume:
  react-volume: